service: aula2-serverless

frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  createCostumer:
    handler: src/application/costumer/functions/createCostumer.execute
    events:
      - http:
          path: costumers
          method: post
  listCostumers:
    handler: src/application/costumer/functions/listCostumers.execute
    events:
      - http:
          path: costumers
          method: get
